version: '3.1'

services:
  # database
  db:
    image: mysql:5.7
    container_name: laradocker_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: laradocker
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  adminer:
    container_name: laradocker_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080      

  # laravel, php fpm, java,..
  app:
    container_name: laradocker_app
    image: laradocker_php_app
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile 
    volumes:
      - .:/var/www/html/

    
    depends_on:
      - db

  # webserver
  webserver:
    container_name: laradocker_webserver
    image: nginx
    ports:
      - 8888:80

    volumes:
      - .:/var/www/html/
      - ./docker/webserver_config.conf:/etc/nginx/conf.d/default.conf

    command: /bin/sh -c "nginx -g 'daemon off;'"
    links:
      - app

#volumes:



## comment222


