version: '2.0'
services:
  web:
    image: php:7.4-fpm
    volumes:
    - logvolume01:/var/log
    links:
    - cache
  cache:
    image: redis
    ports:
      - 6379:6379
volumes:
  logvolume01: {}
