version: '3.1'

services:
  # database
  # db:
  #   image: mysql:5.7
  #   container_name: dockerjava_database
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_DATABASE: dockerjava
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass

  # adminer:
  #   container_name: dockerjava_adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080      

  # run java, jar files.
  app:
    container_name: dockerjava_app
    image: openjdk:8-jdk-alpine
    volumes:
      - .:/usr/src/myapp
    # compile and run java class file
    command: sh -c "java -version && cd /usr/src/myapp && javac Main.java && java Main"      
    # depends_on:
    #   - db

  # webserver
  # webserver:
  #   container_name: dockerjava_webserver
  #   image: nginx
  #   ports:
  #     - 8888:80

  #   volumes:
  #     - .:/var/www/html/
  #     - ./docker/webserver_config.conf:/etc/nginx/conf.d/default.conf

  #   command: /bin/sh -c "nginx -g 'daemon off;'"
  #   links:
  #     - app

#volumes:

